### ISSUE TITLE
Add cake-contrib user

### ISSUE THREAD

**Issue by gep13** [cake-contrib/cake.asciidoctorj#1]
First of all, I wanted to thank you for adding to the Cake community by adding this addin.

I was just wondering if you had seen this blog post:

http://cakebuild.net/blog/2016/08/cake-contribution-organization

We are currently going through a process of increasing the visibility of addins, and also trying to ensure their long term maintainability.

To that end, we are asking addin creators to add the cake-contrib user on NuGet as a co-owner (this can be done through the NuGet website by clicking on Manage Owners on the package page).

Would you be interested in doing this? If you have any questions about this, please let me know. There was some initial concern that the Cake Team were trying to "take over" packages, and that couldn't be further from the truth, and if you have this concern, or others, I would like to address them.

Thanks!

**Comment by nils-a** [comment]
I had not seen that post, no.
I have added the cake-contrib user as a co-owner in NuGet.
If you add me to the cake-contrib organization, I'll move the repo accordingly.

**Comment by gep13** [comment]
@nils-a thanks for doing that!  I really appreciate it!

Regarding moving the repository into the Organisation on GitHub, that is definitely something that we can do.

The full process for moving an addin repository into the Organisation is documented here:

https://github.com/cake-contrib/Home#how-do-i-as-an-addin-author-transfer-a-repository-to-the-organisation

Due to a limitation of GitHub, the initial transfer of the repository needs to happen to an individual's account, i.e mine (gep13) and from there, I would move it into the Organisation, and give you all the required permissions.

How does that sound?

**Comment by nils-a** [comment]
I'll transfer it now.

**Comment by gep13** [comment]
@nils-a I have transferred the repository, and invited you to the Cake Contrib Organisation.

Can you let me know if you use Twitter/Slack?  I would like to follow your account from the Cake-Contrib Twitter account, and also invite you to the Cake-Contrib Slack Team.  This gives means of communication in case you have any questions.

I have a little bit of extra work to do to setup an AppVeyor build for the project, which is typically what we use for addins.  I see that you already have an alternative CI system in place, which is perfectly fine, this will just be an additional one.

Please let me know if you have any questions.

**Comment by gep13** [comment]
@nils-a there are still some permissions that are syncing, but you should have access to everything that you need.  Please let me know if you have any questions.

**Comment by nils-a** [comment]
No questions, thanks!
twitter is @nils_andresen and I created a slack account under nils@nils-andresen.de.
Up to now I have mostly used DevOps for CI, here I tested gitlab: I'm perfectly willing to switch to AppVeyor 👍

**Comment by gep13** [comment]
@nils-a I have sent you an invite to join the Slack Team.

Perfect.  The AppVeyor build is all setup, and if you sign into it with your GitHub account, you should have access to the project that I created.

**Comment by gep13** [comment]
We have the option of using Azure DevOps as well, and @pascalberger would be able to help with setting up your access to that.
