### ISSUE TITLE
rename the master-branch to main

### ISSUE THREAD

**Issue by nils-a** [cake-contrib/cake.asciidoctorj#14]
rationale : https://tools.ietf.org/id/draft-knodel-terminology-00.html#rfc.section.1.1.1

**Comment by nils-a** [comment]
@gep13 : You still maintain a fork of this repository. I'm not sure what the procedure is in this case...

Would you be ok with re-forking? Alternatively we could do some testing whether gh can simply cope with the rename across forks.

**Comment by gep13** [comment]
@nils-a it is unlikely that GitHub will do anything to help with the rename of the branch currently. I believe that they are working on “something” to help with this, but not available yet.

I have no objections to you doing the rename and I can update my fork to match the change.

**Comment by nils-a** [comment]
@gep13 it's done.

**Comment by gep13** [comment]
Great work!
