### ISSUE TITLE
The "Require" parameter option has not the correct type

### ISSUE THREAD

**Issue by mcpride** [cake-contrib/cake.asciidoctorj#194]
In the current implementation the `Require` property in `AsciiDoctorJRunnerSettings` is implemented as `bool` (switch) but it has to be implemented as an `List<string>`, so that required extension libraries can be added via that parameter. 

Possible values for example are:

- `asciidoctor-diagram`
- `asciidoctor-epub3`
- `asciidoctor-revealjs`

The values then should be added as comma-separated list like `--require "asciidoctor-diagram,asciidoctor-epub3,asciidoctor-revealjs"` or as multiple parameters like  `--require asciidoctor-diagram --require asciidoctor-epub3 --require asciidoctor-revealjs`

**Comment by nils-a** [comment]
@all-contributors please add @mcpride for bug.
