### ISSUE TITLE
Publishing of documentation is broken

### ISSUE THREAD

**Issue by nils-a** [cake-contrib/cake.asciidoctorj#31]
Error is:

>Executing: "D:/a/cake.asciidoctorj/cake.asciidoctorj/tools/kudusync.exe" --from "D:/a/cake.asciidoctorj/cake.asciidoctorj/BuildArtifacts/Documentation" --to "D:/a/cake.asciidoctorj/cake.asciidoctorj/BuildArtifacts/temp/_PublishedDocumentation/20200916_060219" --ignoremanifest --perf --ignore ".git;CNAME"
>Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'CommandLine, Version=2.8.0.0, Culture=neutral, PublicKeyToken=5a870481e358d379'. The system cannot find the file specified.
>File name: 'CommandLine, Version=2.8.0.0, Culture=neutral, PublicKeyToken=5a870481e358d379'
>   at KuduSync.NET.Program.Main(String[] args)

**Comment by gep13** [comment]
@nils-a this s a "known" issue :(

If you change your pre-processor directive to:

```
#load nuget:https://ci.appveyor.com/nuget/cake-recipe?package=Cake.Recipe&version=2.0.0-alpha0456&prerelease
```

It should work.

**Comment by gep13** [comment]
@AdmiringWorm spotted this problem when he was building Cake.Transifex, and we resolved it over there.

**Comment by AdmiringWorm** [comment]
Update.
@gep13 posted the wrong version, at minimum to have documentation to work again, you need to update to version `2.0.0-alpha0462`
```cs
#load nuget:https://ci.appveyor.com/nuget/cake-recipe?package=Cake.Recipe&version=2.0.0-alpha0462&prerelease
```

**Comment by gep13** [comment]
I copied the one out of Cake.Transifex, assuming that was the minimum required 😸

**Comment by AdmiringWorm** [comment]
nope, just haven't updated the develop branch yet on Cake.Transifex

**Comment by gep13** [comment]
Doh! Apologies!
