### ISSUE TITLE
Add more documentation

### ISSUE THREAD

**Issue by nils-a** [cake-contrib/cake.asciidoctorj#4]
- [ ] The documentation at https://cakebuild.net/api/Cake.AsciiDoctorJ/ is still missing some explanations
- [ ] Add Wyam documentation

**Comment by gep13** [comment]
@nils-a just wanted to touch base to make sure that you were aware that building a Wyam docs site is already built into Cake.Recipe.  If you create a `gh-pages` branch on this repository, it will publish all the docs to there.

For creating that branch, you can follow the steps here:

https://www.gep13.co.uk/blog/how-to-create-gh-pages-branch

**Comment by gep13** [comment]
@nils-a hmm, this is a little strange...

Everything I can see suggests that the Wyam site should have been published, but it doesn't look like it has been. 😕

**Comment by nils-a** [comment]
That's probably because I'm an .... äh.. no so adept at reading documentation..
docs said..

```
git checkout --orphan gh-pages
git rm -rf .
echo "My Page" > index.html
git add index.html
git commit -a -m "First pages commit"
git push --set-upstream origin gh-pages
```

If, however, one does
```
git checkout --orphan gh-pages
git rm -rf .
git commit --allow-empty -m "an empty commit"
git push --set-upstream origin gh-pages
```

publishing the docs does not work.
Though I'm not sure whether that is a "bug" in Cake.Recipe or simple stupidity on my part..

**Comment by gep13** [comment]
Hmm, could be that this could cause problems within Cake.Recipe.  It uses some git commands to establish what has changed, if anything, before commiting changes to branch.  Glad you got it sorted though!
